# Generated by Django 5.0.2 on 2024-03-19 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_assigntask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignTask',
        ),
    ]
