# Generated by Django 5.0.2 on 2024-03-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_project_enddate_alter_project_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='projectmodule',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
