# Generated by Django 5.0.2 on 2024-03-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_generatedreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratedReport',
        ),
    ]
